name: amd64 deb11 iso

on:
  push:
    paths:
    - 'debian/*.sh'
    - 'debian/preseed.cfg'
    - 'Makefile'
    - '.github/workflows/build_*.yml'

  pull_request:
    paths:
    - 'debian/*.sh'
    - 'preseed.cfg'
    - 'Makefile'
    - '.github/workflows/build_*.yml'
    
jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libarchive-tools cpio xorriso curl

      - name: Build iso
        run: make debian-build-amd64