---
name: debian amd64

on:
  push:
    paths:
    - 'debian/*'
    - 'Makefile'
    - '.github/workflows/build_amd64.yml'

  pull_request:
    paths:
    - 'debian/*'
    - 'Makefile'
    - '.github/workflows/build_amd64.yml'

  workflow_dispatch:

jobs:
  build-debian-amd64:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@main
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libarchive-tools cpio xorriso curl

      - name: Build iso
        run: make build-debian-amd64

      - uses: actions/upload-artifact@main
        with:
          name: retronas-debian-amd64-${{ github.sha }}
          path: |
            tmp/*.iso
          if-no-files-found: error
