---
name: rpios arm64

on:
  push:
    paths:
    - 'rpios/*'
    - 'Makefile'
    - '.github/workflows/rpios_arm64.yml'

  pull_request:
    paths:
    - 'rpios/*'
    - 'Makefile'
    - '.github/workflows/rpios_arm64.yml'

  workflow_dispatch:

jobs:
  build-arm64:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@main
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl qemu-user-static binfmt-support

      - name: Build image
        run: make build-rpios-arm64

      - uses: actions/upload-artifact@main
        with:
          name: retronas-rpios-arm64-${{ github.sha }}
          path: |
            rpios/tmp/*arm64-lite.img
          if-no-files-found: error
