---
name: rpios arm64

on:
  push:
    paths:
      - 'rpios/*'
      - 'Makefile'
      - '.github/workflows/rpios_arm64.yml'
    tags:
      - "*"

  pull_request:
    paths:
      - 'rpios/*'
      - 'Makefile'
      - '.github/workflows/rpios_arm64.yml'

  workflow_dispatch:

jobs:
  build-arm64:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@main
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xz-utils wget curl qemu-user-static binfmt-support

      - name: Build image
        run: make build-rpios-arm64

      - name: Compress Image
        run: |
          cd rpios/tmp
          xz -z -6 *arm64-lite.img

      - uses: actions/upload-artifact@main
        with:
          name: retronas-rpios-arm64-${{ github.sha }}
          path: |
            rpios/tmp/*arm64-lite.img.xz
          compression-level: 0
          if-no-files-found: error


      - uses: softprops/action-gh-release
        if: github.ref_type == 'tag'
        with:
          files:
            rpios/tmp/*arm64-lite.img.xz
